### ISSUE TITLE
1.5.0 support

### ISSUE THREAD

**Issue by gunr2171** [superrob/BeatSaberMultiplayer#7]
Are you planning on updating this repo to support 1.5.0 or should I move this issue over to the main repo?

**Comment by superrob** [comment]
Any issues with 1.5.0? 
Havn't tried 1.5.0 myself, so would be helpfull if you know anything isn't working.

**Comment by gunr2171** [comment]
It seems between when I wrote this and now the other mods have updated and the multiplayer mod at least loads and shows up in the main menu. Unfortunately I haven't had a chance to try it with my friends yet.
